#!/bin/bash

# README
# This script processes a list of folder names and fasta file pairs from an input file to run SibeliaZ and maf2synteny tools.
# Each line in the input file should contain a folder name and two fasta file paths separated by tabs.
# The script will create directories, change to those directories, run SibeliaZ on the fasta files, 
# and then run maf2synteny on the resulting alignment files.

# Author: Bloodmark

# Input details:
# - Input file: /home/bloodmark/workarea/synteny/synteny_filepath.txt
#   - Each line should contain three tab-separated values: folder_name, fasta_file1, fasta_file2

# Output details:
# - For each line in the input file:
#   - A new directory named after the folder_name will be created.
#   - SibeliaZ will be run on the two fasta files.
#   - maf2synteny will be run on the alignment file generated by SibeliaZ.

# Script functioning:
# 1. Define the input file containing three columns (folder_name, fasta_file1, fasta_file2).
# 2. Loop through each line in the input file.
# 3. Create a directory for each folder_name.
# 4. Change to the newly created directory.
# 5. Run SibeliaZ on the specified fasta files.
# 6. Run maf2synteny on the alignment file generated by SibeliaZ.
# 7. Move back to the original directory.

# Example of running the script:
# bash synteny_script.sh

# Note: Ensure SibeliaZ and maf2synteny are installed and accessible in your PATH.

# Code starts below:

# Define the input file containing three columns
input_file="/home/bloodmark/workarea/synteny/synteny_filepath.txt"

# Check if the input file exists
if [ ! -f "$input_file" ]; then
    echo "Error: File '$input_file' not found!"
    exit 1
fi

# Loop through each line in the input file
while IFS=$'\t' read -r folder_name fasta_file1 fasta_file2; do
    # Create directories
    mkdir -p "/home/bloodmark/workarea/synteny/$folder_name"

    # Change directory
    cd "/home/bloodmark/workarea/synteny/$folder_name" || exit

    # Run sibeliaz
    if ! sibeliaz "$fasta_file1" "$fasta_file2"; then
        echo "Error: SibeliaZ failed for $folder_name"
        continue
    fi

    # Run maf2synteny
    if ! maf2synteny sibeliaz_out/alignment.maf; then
        echo "Error: maf2synteny failed for $folder_name"
        continue
    fi

    # Move back to the original directory
    cd - || exit

done < "$input_file"

echo "Processing completed."

